### ISSUE TITLE
Date scheduled in tasks and dataview format is not visible beyond one week

### ISSUE THREAD

**Issue by HochuSirok** [j-palindrome/obsidian-time-ruler#100]
First off: thank you so much for your plugin. I like it much better than the similar day planner (although the day planner can show the Now line in the middle of the task, which better shows what time I am in). Easy scheduling and support for different metadata formats is cool.

**Describe the bug**
If you schedule a date (scheduled or ⏳️) in tasks or dataview format - tasks will be visible no further than a week (next 7 days). 

**To Reproduce**
1. Create a new obsidian vault.
2. Download plugins dataview, tasks, time ruler.
3. Create a task with date <today's date> + 7 days: write the text manually or create through time ruler interface.
4. The task is not visible on the timeline.

**Expected behavior**
Expect to see a task on the timeline.

**Screenshots**
![time ruler 1](https://github.com/joshuatazrein/obsidian-time-ruler/assets/137641387/0d1d0307-ac6e-4434-95e4-a137287901e2)
![time ruler 2](https://github.com/joshuatazrein/obsidian-time-ruler/assets/137641387/421c4b2b-d949-48b7-a8b3-7cf679ee7562)
![time ruler 3](https://github.com/joshuatazrein/obsidian-time-ruler/assets/137641387/ab578c0b-ea5e-45f8-a0f1-e7e97c90ab2a)
![time ruler 4](https://github.com/joshuatazrein/obsidian-time-ruler/assets/137641387/f67ca6a9-e945-4afd-893f-7a6e0c1aed85)

**Obsidian Version:**  
- [x] Mobile
- [x] Desktop

**Additional context**
The dates of tasks due and 📆 can be seen on the timeline. Dates set in day planner and full calendar format are also visible (see screenshots).

**Comment by HochuSirok** [comment]
Greetings! Any news?

**Comment by j-palindrome** [comment]
Sorry for the delay on this—I'm looking into it right now.

**Comment by j-palindrome** [comment]
This is fixed as of the upcoming version.
