### ISSUE TITLE
Add option to show tasks individually even if they are nested

### ISSUE THREAD

**Issue by higalpe** [j-palindrome/obsidian-time-ruler#106]
Sometimes it is kind of messy to visualize only the tasks for a specific date if they are nested. 
Lets say we have this simple use case:

Epic task 1 (level 1)
group task 1 (level 2)
task 1 (level 3)
task 2 (level 3)
task n (levle 3)

Epic task 2 (level 1)
...

So far this looks like this inside the ruler window
![imagen](https://github.com/joshuatazrein/obsidian-time-ruler/assets/42850993/b0a05d37-131b-4d2d-84cd-4305ff45f71c)

As mentioned, each epic or group task could have a lot of tasks inside that usually I do not want to visualize if they are not planned for today. Actually if I need to work on three different epics on the same day, time ruler will show EVERYTHING inside each epic. So it gets no very confortable to use.

**Describe the solution you'd like**
I would like to have an option to visualize the ALL tasks (even the parents) but without the current nested view and only if they are planned for the day I am checking. Just individual tasks placed at the corresponding due date.

That is, if we have:
Epic task 1 (level 1) -> due 2024-03-31
group task 1 (level 2) -> due 2024-03-29
task 1 (level 3) -> due 2024-03-27
task 2 (level 3)

If check only day 27 on the time ruler calendar, I should see only task 1 appearing.

**UPDATE:**
🤔 ok, just realised that using scheduled instead of due kinf of fix this issue and maybe I can survive with it, but:
1. It force me to use "scheduled" for everything. 
2. Task parent nodes still showing all the tasks they contain.
![imagen](https://github.com/joshuatazrein/obsidian-time-ruler/assets/42850993/670b54bc-7342-4c9e-af0d-e43de32527a3)

**It would be nice to have a option to activate/deactivate the "individual task display behaviour" for both scheduled and due dates as described.**

Thank you!! This is a nice plugin!

**Comment by higalpe** [comment]
By the way, if you want a reference to play with and better understand the feature, both [task calendar view](https://github.com/702573N/Obsidian-Tasks-Calendar) and [task time line](https://github.com/702573N/Obsidian-Tasks-Timeline) snippets display the tasks using this "individual" approach. That would be the feature I am talking about.

**Comment by joshuatazrein** [comment]
The upcoming release features an option to only show tasks which are scheduled. So if a subtask is not scheduled, it won't show up in Time Ruler making it easier to see which ones need to be done. Would that help?

**Comment by higalpe** [comment]
That is definetively a good feature, but the use case I showed is a different problem. 
It does nto solve the problem of having 2 or three nested tasks with different due/scheduled dates. That is, for a use case like the one presented, right now, time ruler will show ALL the tasks inside one node even if only one of its child tasks is scheduled (or due) for today. 

- [ ] #epic This is an epic 1 📅 2024-04-09
	- [ ] #group This is a group task 📅 2024-04-05 #test
		- [ ] This is a normal task 📅 2024-04-02

I think that only showing the tasks that really are expected for a specific day is maybe more intuitive or less noisy. A behaviour like the mentioned task calendar view or the Agenda from Logseq.

If you are interested, let me know if you need more info or details of the use case : )

**Comment by j-palindrome** [comment]
There's an option to only show tasks scheduled for the current day.
