### ISSUE TITLE
Adjusting the duration does not work properly

### ISSUE THREAD

**Issue by nerumi** [j-palindrome/obsidian-time-ruler#111]
**Describe the bug**
Adjusting the duration of a task adds a second duration property in ISO8601 standard (something like "PT2H") to the task making it impossible for Time Ruler to display the correct duration presumably due to conflicting information.

**To Reproduce**
1. Create a Test vault
2. Install Dataview and Time Ruler
3. Write a Test Task on the "Welcome" page
4. Go to Time Ruler and schedule the task to any day and time
5. Use Time Ruler to set a arbitrary duration
6. Use Time Ruler to adjust the duration

**Expected behavior**
The task should be displayed with its new duration.

**Actual behavior**
The task reverts back to the way it's displayed when no duration is set.

**Screenshots**
n/a

**Obsidian Version:** 
- [?] Mobile
- [x] Desktop 1.5.12

**Additional context**
Adjusting the duration of the task repeatedly keeps adding ISO8601 duration strings to the new duration property array.

**Comment by gypsyav** [comment]
I can confirm this behavior.

**Comment by j-palindrome** [comment]
This is fixed in the upcoming release!
