### ISSUE TITLE
Emoji are displayed incorrectly when Tasks metadata fields are present

### ISSUE THREAD

**Issue by HochuSirok** [j-palindrome/obsidian-time-ruler#113]
**Describe the bug**
Emoji are displayed incorrectly when Tasks metadata fields are present (see screenshot)

**To Reproduce**
1. Set TimeRuler and DataView
2. Create tasks as in the screenshot
3. See incorrectly displayed � instead of emoji.

**Screenshots**
![Screenshot_20240419_143921](https://github.com/j-palindrome/obsidian-time-ruler/assets/137641387/d9ce92f0-b521-4065-b3df-d9ff3b50c69f)

**Obsidian Version:** 
- [x] Mobile
- [x] Desktop

**Comment by j-palindrome** [comment]
This is fixed in the upcoming release.
