### ISSUE TITLE
Tags with paths in them are copied into the title

### ISSUE THREAD

**Issue by jadedarko** [j-palindrome/obsidian-time-ruler#116]
**Describe the bug**
Tasks with tags that have paths in them have the path pulled into the title.

**To Reproduce**

1. Create a task has a tag with a path in it, such as `#work/admin`:
```
- [ ] timesheet & recap #work/admin  [scheduled:: 2024-04-30T17:15]  [duration:: 15m]
```

2. Note that any elements after the path separator are pulled into the title:
<img width="211" alt="Screenshot 2024-04-30 at 17 02 39" src="https://github.com/j-palindrome/obsidian-time-ruler/assets/2138067/1a520df3-02db-46bb-9a2a-a452221d3667">

3. If the task is then rescheduled by dragging in the timeline view, the partial tag is then duplicated:
```
- [ ] timesheet & recap /admin #work/admin [duration:: PT15M]  [scheduled:: 2024-04-30T17:30]  [duration:: 15m]
```
<img width="261" alt="Screenshot 2024-04-30 at 17 05 39" src="https://github.com/j-palindrome/obsidian-time-ruler/assets/2138067/1264cd19-cb05-451d-992b-a4d1a48452c2">

**Expected behavior**
Tags with paths in them are treated as tags, and not:
1. pulled into the title
2. copied when the task is rescheduled

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

**Comment by j-palindrome** [comment]
This is fixed in the upcoming release.

**Comment by lxmwwl** [comment]
> This is fixed in the upcoming release.这在即将发布的版本中得到了修复。

在最新版中没有被修复
