### ISSUE TITLE
hi I can't get Time Ruler to detect. full calendar daily note task events

### ISSUE THREAD

**Issue by MaddyDragon** [j-palindrome/obsidian-time-ruler#119]
**Describe the bug**
I can't get time ruler to detect full calendar daily note task events 

**To Reproduce**
1. create event in full calendar under the 'daily note' calendar, and select task event 
2. open time ruler 
3. events not appearing 

**Expected behavior**
1. create event in full calendar under the 'daily note' calendar, and select task event 
2. open time ruler 
3. see task events 

**Obsidian Version:** 
- [ ] Desktop (Mac)

**Comment by j-palindrome** [comment]
This seems to be a consistent issue I'll try to fix on the next release. Thanks!

**Comment by j-palindrome** [comment]
Daily Note events in Full Calendar will show up in Time Ruler like this:
<img width="781" alt="Screenshot 2024-06-02 at 12 11 19 AM" src="https://github.com/j-palindrome/obsidian-time-ruler/assets/84872947/4197cc58-ed91-44fd-916b-85a31761624a">
