### ISSUE TITLE
Things TODAY/in full calendar could not show on time ruler.

### ISSUE THREAD

**Issue by yoghurtdewdew** [j-palindrome/obsidian-time-ruler#120]
**Describe the bug**
1️⃣ Things TODAY show on YESTERDAY of time ruler.
2️⃣ Things in full calendar could not show on time ruler.

**To Reproduce**
day planner format & full calendar format → time ruler.

**Expected behavior**
1️⃣ Things TODAY show on TODAY of time ruler.
2️⃣ Things in full calendar show on time ruler.

**Screenshots**
1️⃣ Things TODAY show on YESTERDAY of time ruler.
<img width="1193" alt="image" src="https://github.com/j-palindrome/obsidian-time-ruler/assets/63794438/058932a2-9bbe-4cf6-a395-c25051452bcd">
2️⃣ Things in full calendar could not show on time ruler.
<img width="1302" alt="image" src="https://github.com/j-palindrome/obsidian-time-ruler/assets/63794438/58bc575f-7c05-458e-b23e-7930cd6c960a">

**Obsidian Version:** 
Desktop v 1.5.12 (MacOS)

**Comment by j-palindrome** [comment]
Thanks, I'll see if I can reproduce.

**Comment by j-palindrome** [comment]
I'm having a hard time reproducing this issue. Can you send your settings in Time Ruler as a screenshot?
