### ISSUE TITLE
Add hyperlink support for external calendar event locations

### ISSUE THREAD

**Issue by ForeverFloating** [j-palindrome/obsidian-time-ruler#121]
**Is your feature request related to a problem? Please describe.**
Some of my Google Calendar events have hyperlinks either in the Location field (for example, for virtual events with an invitation link). While the text in the location field does appear in the Time Ruler, the links are not hyperlinked so I cannot click them to open the event location.

**Describe the solution you'd like**
I would like synced Google Calendar events that have hyperlinks in the Location field to be clickable when shown in the Time Ruler plugin.

**Comment by j-palindrome** [comment]
Yes, this would be a good thing to do. I can see what the Obsidian API has to support hyperlinks.
