### ISSUE TITLE
Unexpected result when checking off a recurring task

### ISSUE THREAD

**Issue by joellti** [j-palindrome/obsidian-time-ruler#122]
**Describe the bug**
There are several ways to finish a recurring task. When I do it at the task line, or in Tasks codeblocks the behavior is consistent with the settings in Tasks plugin. But if I do the same in Time Ruler, I notice at two inconsistent behaviors
- The future task is not created
- The completion field is added even when the Tasks setting has this option turned off.

**To Reproduce**
1. Create a dummy recurring task in Tasks format
2. Click the task radio button to mark it complete
3. See stated behavior

**Expected behavior**
I want the behavior of Time Ruler to be consistent with other methods.

**Screenshots**

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

**Additional context**

**Comment by j-palindrome** [comment]
I'll try to fix this issue in the next update.
