### ISSUE TITLE
Support for tasks queries in addition to dataview

### ISSUE THREAD

**Issue by jenpritchard** [j-palindrome/obsidian-time-ruler#123]
**Is your feature request related to a problem? Please describe.**
Right now, the filter function only accepts a Dataview query. Although that handles most scenarios someone would want, Dataview doesn't support queries for "blocked"/"blocking" tasks, and recurring tasks. I would like to filter out any tasks that are currently blocked, but I can't figure out a way to do this.

**Describe the solution you'd like**
Offer the option of using a tasks query instead of Dataview (especially if someone has chosen Tasks as their preferred field format)

**Describe alternatives you've considered**
The only pseudo-work around I can think of is to filter out tasks based on seeing the ⛔ symbol in the text, but I haven't been able to get that to work either. It's also not ideal since a task may have a ⛔ marked, but the task it was blocked by is now complete and hence it's actually *not* blocked anymore. In cases like that, a task could be filtered out by mistake, and I'd have to be aware of its absence, go remove the symbol from the task, and hopefully I didn't want to keep it for informational purposes.

**Comment by j-palindrome** [comment]
Tasks Emojis and Dataview queries are a bit difficult to be compatible. There is a Tasks API that may support queries, so I can look into that. Added to roadmap!

**Comment by brodmo** [comment]
So how do I query for blocked tasks? I can't figure this out
