### ISSUE TITLE
add option to save all time-block section in daily note for future overviewing

### ISSUE THREAD

**Issue by Jimmy2times** [j-palindrome/obsidian-time-ruler#125]
Just a suggestion. As I was experimenting with recurring task, I found out if I drag the same task to the next day, today's session got removed. So an idea occurred to me that an option to save all time-block section would be of great convenience _if I want to review all my activity of that day_. Which means the week view maybe need a switch between querying from task of various notes or saved section from daily notes.
Btw, a question, can the date and time field be separated when editing via time ruler? Task plugin failed to query my tasks when the date and time are in the same bracket (e.g. [scheduled:: 2024-07-02T19:00]).
Thank you for your great work, from a fellow dreamer who still hope to manage task in obsidian.

**Comment by j-palindrome** [comment]
If you use Full Calendar format ([date:: xxxx-xx-xx]  [startTime:: 14:30]) you can separate these. Not sure if that helps. But I can try to fix this when format is set to Tasks. Added to roadmap.
