### ISSUE TITLE
Non-times parsed as times, AM/PM ignored. 

### ISSUE THREAD

**Issue by technotherion** [j-palindrome/obsidian-time-ruler#129]
For tasks within the day's daily note:

Task "11:30PM - Get in bed" is shown as being at 11:30AM 
![image](https://github.com/user-attachments/assets/6c529b98-02a4-4cee-8ead-d20ebe17b0e9)

Task "- [ ] 1 hour of decluttering/organizing life " shown as being at 1AM albeit being unscheduled
![image](https://github.com/user-attachments/assets/62eb8d62-22e0-4d1b-b8de-3dd8f237ca03)

When dragging a task to a PM time via the timeline, a 24 hour timestamp is used. (The time displayed here is not relevant, I just dragged and dropped it to a random PM time)
![image](https://github.com/user-attachments/assets/85c2a8b3-89b5-4aed-824b-41ec4659d430)

I'm using Time Ruler 2.4.0 with Tasks format selected using 12 hour format.

**Comment by j-palindrome** [comment]
We only use 24 hour time in Time Ruler right now. I can add AM/PM support to the roadmap.
