### ISSUE TITLE
The ongoing task cannot be displayed

### ISSUE THREAD

**Issue by xyy-1997** [j-palindrome/obsidian-time-ruler#132]
**Describe the bug**
Tasks whose start time is earlier than the current time cannot be displayed in time ruler. As a result, I cannot see what I should do now and cannot directly choose to complete the task after completing it.

**To Reproduce**
1. Go to any md file
2. Add a task that starts earlier than now
3. Scroll down to today page in time ruler

**Expected behavior**
I want to be able to see today's ongoing tasks or today's unfinished tasks in the time ruler.

**Screenshots**
Not ongoing.
![image](https://github.com/user-attachments/assets/cfb6f6df-1227-4bc7-bb38-a4a0863b7ae5)
Ongoing.
![image](https://github.com/user-attachments/assets/5a2ff73c-029c-4ad2-9ab4-2065950dfa82)

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

**Additional context**

**Comment by xyy-1997** [comment]
To clarify, the tasks in {{today}}.md will be displayed in the 'past' section, but tasks from previous files will not be displayed

**Comment by xyy-1997** [comment]
V2.4.0 is ok for me.
![image](https://github.com/user-attachments/assets/282b7156-2f92-400a-bca5-e9e207c35fe5)

**Comment by j-palindrome** [comment]
Great!
