### ISSUE TITLE
Support for private iCal

### ISSUE THREAD

**Issue by yerenutku** [j-palindrome/obsidian-time-ruler#145]
**Is your feature request related to a problem? Please describe.**
I wish to integrate my online calendar into this plugin however it requires me to make my calendar public. iCal public is not safe and there is a private version `Use this address to access this calendar from other applications without making it public.` unfortunately that doesn't work in the plugin. When secret iCal address is provided, then the plugin throws an error 
```
TypeError: Cannot read properties of undefined (reading 'includes')
    at eval (plugin:time-ruler:72257:31)
    at async Promise.all (index 0)
    at async CalendarAPI.loadEvents (plugin:time-ruler:72292:5)
eval	@	plugin:time-ruler:72284
```

**Describe the solution you'd like**
Adding support for secret addresses in iCall.

**Describe alternatives you've considered**
I do not consider making my calendar public which I found very unsafe.

**Additional context**
<img width="660" alt="image" src="https://github.com/user-attachments/assets/cfb1d3b4-032d-4d72-9c33-2ab715f6aa81" />

**Comment by j-palindrome** [comment]
Copy the "Secret address" and paste it into the URL, that should work.

**Comment by yerenutku** [comment]
If this feature is already supported you can consider this as a bug report then. I tried and it doesn't pull any events. And throws the error that I shared in my initial report.
