### ISSUE TITLE
Wrong date

### ISSUE THREAD

**Issue by Ekb18** [j-palindrome/obsidian-time-ruler#85]
**Describe the bug**
For some reason, Time Ruler is registering the wrong date. It's registering today's date as yesterday's date, while registering tomorrow's date as today's date.

**To Reproduce**
1. Create test vault
2. Install Dataview and Time-ruler
3. Create Today's Daily Note and add a planning,
4. Open Time-ruler
5. See error

**Expected behavior**
The dates in time-ruler should be correct. 

**Screenshots**
![Screenshot 2023-11-28 192147](https://github.com/joshuatazrein/obsidian-time-ruler/assets/152311980/04217798-ebe4-4d48-abc4-43c38a8ffc38)

**Obsidian Version:** 
- [ ] Mobile
- [x] Desktop

**Comment by joshuatazrein** [comment]
Thanks, I'll try to fix this as soon as I get the chance. Added to roadmap

**Comment by jckoester** [comment]
Having the same problem using the most standard date format `YYYY-MM-DD` in all option fields.  Seems like in genral the daily notes are parsed incorrectly...

**Comment by joshuatazrein** [comment]
Do you have daily notes disabled? It only reads from the `daily-notes.json` settings file to parse daily note information.

**Comment by joshuatazrein** [comment]
Hm, I can't reproduce this error. Can you post a screenshot?

**Comment by jckoester** [comment]
In my test vault I was using the original `daily-notes`, in my main vault I prefer periodic notes, but that does not seem to be the problem.

I was wondering if localization might be the problem, as I'm using obsidian in German. Changing the language alone doesn't change anything though. Do you know any other settings I might try?

**Screenshots:**
![Screenshot 2024-01-04 211707](https://github.com/joshuatazrein/obsidian-time-ruler/assets/777345/605ccc4d-4609-4e2d-b70d-00f01212f659)
![Screenshot 2024-01-04 211724](https://github.com/joshuatazrein/obsidian-time-ruler/assets/777345/a3ae1a2d-0d00-4a31-80e8-af954a7dd78a)
![Screenshot 2024-01-04 211805](https://github.com/joshuatazrein/obsidian-time-ruler/assets/777345/90a3fdf5-e970-459a-8904-1cb661583b2f)
![Screenshot 2024-01-04 211825](https://github.com/joshuatazrein/obsidian-time-ruler/assets/777345/35254e43-04e0-4c84-aedf-1b31404bec73)
![Screenshot 2024-01-04 211309](https://github.com/joshuatazrein/obsidian-time-ruler/assets/777345/d53f3acd-3296-4fb6-a13e-5051398daade)
![Screenshot 2024-01-04 211502](https://github.com/joshuatazrein/obsidian-time-ruler/assets/777345/7d34a218-da11-4365-89c2-3236bdb669f9)
![Screenshot 2024-01-04 211512](https://github.com/joshuatazrein/obsidian-time-ruler/assets/777345/748fd904-9217-436a-b680-20168fbd45f4)

**Comment by joshuatazrein** [comment]
There's a new version with a "Now" mode—not sure if that will fix it but try updating to see if it solves the issue

**Comment by joshuatazrein** [comment]
Also is this only with daily notes or with explicitly scheduled tasks as well?

**Comment by jckoester** [comment]
The "now" mode shows both, but they don't show up in the days anymore. 
If I put a date to the planner entry explicitly (by inline property) evrything works as expected.
![Screenshot 2024-01-04 212940](https://github.com/joshuatazrein/obsidian-time-ruler/assets/777345/ed04a132-ed42-49ef-a034-65da3d620a7a)

**Comment by joshuatazrein** [comment]
I can't reproduce it in my test vault. Here are my settings for Daily Notes.

<img width="1246" alt="Screenshot 2024-01-04 at 12 56 27 PM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/84872947/823595f3-efee-45a0-a8b5-8cdabd0afc53">
<img width="1246" alt="Screenshot 2024-01-04 at 12 56 27 PM" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/84872947/c3e785c5-ed04-4f42-9549-efce210ae925">

**Comment by joshuatazrein** [comment]
Ahh, the localization is probably the issue—`moment.js` is the internal Date library which might adapt to locale.

**Comment by j-palindrome** [comment]
I haven't been able to reproduce—id there's anything else you can provide let me know.
