### ISSUE TITLE
No events in my gmail Calendar shows on the lateral ruler

### ISSUE THREAD

**Issue by amglez** [j-palindrome/obsidian-time-ruler#92]
**Describe the bug**
No events in my gmail Calendar show on the lateral ruler. Tasks from obsidian show fine, but my events do not

**To Reproduce**
I installed "time ruler", made public my calendar and got the ical format link from my gmail calendar:
![imagen](https://github.com/joshuatazrein/obsidian-time-ruler/assets/24720353/792ef6d0-213b-4c84-8559-142d1d78c557)

Then I copied the link in its place, pressed the + sign and got the email name at the bottom of the plugin tab.

**Expected behavior**
I hoped to see my events on the lateral ruler.
**Screenshots**
I did not get them.:
![imagen](https://github.com/joshuatazrein/obsidian-time-ruler/assets/24720353/d416706c-25f9-48b5-9c9b-ae20b83a9202)

**Obsidian Version:** 

- [ ] Desktop v.1.5.3
- [ ] TimeRuler 2.0.3

**Additional context**
My version is Spanish

**Comment by joshuatazrein** [comment]
Thanks for the issue, I'll look into this. Time Ruler doesn't work with repeating events well yet. That night be the issue.

**Comment by amglez** [comment]
Hi
That is quite sad for Time ruler makes little since to me without time blocking, and this calendar feature is great for organising classes.
Thanks for your plug-in and your efford. I will stay tuned.

**Comment by amglez** [comment]
Hi
May be useful: casually, I wrote a note on an event description in my google calendar and I made the change for all future events: when I returned to obsidian for another thing, on reloading time ruler the agenda (the events) appeared. Now I can use it.
I was not doing any testing or something. I just happened. I think it could be of help to understand what is behind the scenes in this issue.
Thanks for your atention

**Comment by abetss** [comment]
Is it possible to show non public calendar as well? When I share the the secret address in ical format

<img width="695" alt="image" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/3966450/7793335f-feb8-4e56-8789-1a57c0243fd5">


I get this error "Time Ruler: Error creating calendar - Cannot add property 1, object is not extensible"
<img width="344" alt="image" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/3966450/0fa1f2fb-a72e-46c0-920c-3f24717738ac">

I know Full Calendar can use the secret address in ical format

**Comment by j-palindrome** [comment]
So far this issue seems to have been fixed.
