### ISSUE TITLE
[Feature Request] Show file basename in UI

### ISSUE THREAD

**Issue by rapatel0** [j-palindrome/obsidian-time-ruler#98]
**Is your feature request related to a problem? Please describe.**
The base name of the file is obscured when there is a moderately long path to a file.  This makes it hard to know which task is being listed.  Example below

<img width="487" alt="image" src="https://github.com/joshuatazrein/obsidian-time-ruler/assets/18704704/791dfdca-5f13-4640-a5df-93e82dc2aa98">

**Describe the solution you'd like**
A few options in priority order
1. Display only the basename of the file
2. Move the full path to the next line
3. Make the columns adjustable

**Describe alternatives you've considered**
I tried hovering over the links to the file, but the UI doesn't work with link previews/ hover editor. 

**Additional context**

**Comment by j-palindrome** [comment]
This is fixed in the upcoming release.
